// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArDaVbZ28ZzfxrjWVN5os-R7u0fh-FRnA',
    appId: '1:299024678136:web:a745f5da61673f524c4f0d',
    messagingSenderId: '299024678136',
    projectId: 'face-scanner-2',
    authDomain: 'face-scanner-2.firebaseapp.com',
    storageBucket: 'face-scanner-2.firebasestorage.app',
    measurementId: 'G-MDDN5KY27T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6N5MGW0OQZ3sW8gTAcu0XoiRsTI1YAMQ',
    appId: '1:299024678136:android:8afe2598f79fda3e4c4f0d',
    messagingSenderId: '299024678136',
    projectId: 'face-scanner-2',
    storageBucket: 'face-scanner-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJOJ079mNlE1-h0LzNX8ORPm-wGj0yyw8',
    appId: '1:299024678136:ios:177b9a049f57b81d4c4f0d',
    messagingSenderId: '299024678136',
    projectId: 'face-scanner-2',
    storageBucket: 'face-scanner-2.firebasestorage.app',
    iosBundleId: 'com.facescanner.ai.beautyanalysis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJOJ079mNlE1-h0LzNX8ORPm-wGj0yyw8',
    appId: '1:299024678136:ios:d28fc1c1e3a7dad24c4f0d',
    messagingSenderId: '299024678136',
    projectId: 'face-scanner-2',
    storageBucket: 'face-scanner-2.firebasestorage.app',
    iosBundleId: 'com.example.faceScanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArDaVbZ28ZzfxrjWVN5os-R7u0fh-FRnA',
    appId: '1:299024678136:web:313be72610220c414c4f0d',
    messagingSenderId: '299024678136',
    projectId: 'face-scanner-2',
    authDomain: 'face-scanner-2.firebaseapp.com',
    storageBucket: 'face-scanner-2.firebasestorage.app',
    measurementId: 'G-E8MPPMW4PZ',
  );

}